<a href="https://colab.research.google.com/github/stanshi2016/pytorch_learning/blob/main/%E5%BC%A0%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch 

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

# tensor相关的函数和运算

In [39]:
torch.empty(5,3)

tensor([[3.4413e-34, 0.0000e+00, 3.5032e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 7.1463e+22, 4.6241e+30],
        [1.0552e+24, 5.5757e-02, 1.8728e+31],
        [5.9571e-02, 7.0374e+22, 1.0177e+31]])

In [8]:
a= torch.randn(5,3) #随机初始化的矩阵,包括以后一些网络模型,想去确认一些维度, 模型结构, 可能需要一些数据投喂
print(a)
a.type()
isinstance(a,torch.FloatTensor)

tensor([[ 0.4439, -0.4880,  0.8345],
        [-1.8258,  0.8870, -1.7187],
        [-2.1372, -1.3248,  1.8699],
        [ 0.1340,  0.0604,  1.1119],
        [-0.2472,  1.0911,  1.4499]])


True

In [23]:
a = torch.ones(2)
a.shape
a

tensor([1., 1.])

In [29]:
a = torch.randn(2,3)
print(a)
a.shape

tensor([[-0.2125,  0.3487,  0.1106],
        [-0.9305, -1.5435,  0.5145]])


torch.Size([2, 3])

In [28]:
a = torch.rand(1,2,3)
print(a)
a.shape

tensor([[[0.6831, 0.1879, 0.9039],
         [0.7637, 0.6026, 0.2383]]])


torch.Size([1, 2, 3])

In [31]:
a = torch.rand(2,3,28,28)
print(a)
#number of element
print(a.numel())


tensor([[[[0.6261, 0.4780, 0.9029,  ..., 0.0170, 0.7079, 0.5700],
          [0.5759, 0.7777, 0.1624,  ..., 0.2332, 0.3689, 0.0304],
          [0.4826, 0.1405, 0.7414,  ..., 0.0722, 0.2723, 0.4731],
          ...,
          [0.2288, 0.1831, 0.0038,  ..., 0.4756, 0.8510, 0.5651],
          [0.7857, 0.9140, 0.4675,  ..., 0.2387, 0.1604, 0.2456],
          [0.5182, 0.9328, 0.3824,  ..., 0.9418, 0.5508, 0.0867]],

         [[0.6129, 0.9834, 0.5727,  ..., 0.9800, 0.5135, 0.1175],
          [0.0432, 0.9553, 0.6526,  ..., 0.1737, 0.3282, 0.7438],
          [0.9419, 0.2419, 0.5693,  ..., 0.9569, 0.4746, 0.3685],
          ...,
          [0.1014, 0.2100, 0.0318,  ..., 0.6533, 0.9005, 0.2846],
          [0.9998, 0.5715, 0.2495,  ..., 0.2854, 0.9201, 0.9925],
          [0.1473, 0.5682, 0.3735,  ..., 0.1784, 0.2156, 0.1310]],

         [[0.2635, 0.7283, 0.1461,  ..., 0.6373, 0.4762, 0.9782],
          [0.0483, 0.1512, 0.8746,  ..., 0.4713, 0.5418, 0.9659],
          [0.2819, 0.9162, 0.2230,  ..., 0

创建Tensor

In [35]:
a = np.array([2,3.3])
torch.from_numpy(a)

a = np.ones([2,3])
torch.from_numpy(a)


tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [38]:
torch.tensor([2.,3.2])
torch.FloatTensor([2.,3.2])
torch.tensor([[2.,3.2], [1.,22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

# 随机初始化


In [40]:
torch.rand(3,3) #0~1均匀采样

tensor([[8.9318e-01, 9.1115e-02, 8.7506e-01],
        [4.1937e-01, 3.9915e-01, 4.4245e-04],
        [9.0303e-01, 9.7889e-01, 8.7829e-01]])

In [41]:
a = torch.rand(3,3)
torch.rand_like(a)

tensor([[0.0120, 0.9759, 0.1010],
        [0.0188, 0.6716, 0.1027],
        [0.1780, 0.5572, 0.1909]])

In [42]:
torch.randint(1,10,[3,3])

tensor([[2, 9, 1],
        [1, 2, 5],
        [4, 1, 4]])

In [43]:
torch.randn(3,3) #N(0,1)均值为0,方差为1

tensor([[ 0.2672, -1.6671, -1.0207],
        [-0.9693,  1.3274,  0.0624],
        [ 0.7183,  0.4622, -0.3749]])

In [44]:
torch.full([2,3],7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [46]:
torch.arange(0,10)
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [50]:
torch.linspace(0,10,steps=4)
torch.linspace(0,10,steps=10)
torch.linspace(0,10,steps=11)
torch.logspace(0,-1,steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [52]:
torch.ones(3,3)
torch.zeros(3,3)
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [56]:
torch.randperm(10)
a = torch.rand(2,3)
print(a)
a[[1,0]]

idx = torch.randperm(2)
a[idx] 


tensor([[0.6007, 0.5841, 0.9029],
        [0.3679, 0.7625, 0.2678]])


tensor([[0.3679, 0.7625, 0.2678],
        [0.6007, 0.5841, 0.9029]])

In [ ]:
torch.zeros(5,3,dtype=torch.long) #x+y 训练这样一个映射,神经网络y truth_label one-hot表示

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.tensor(1.)
torch.tensor(1.3)
a = torch.tensor(2.2)
a.shape
a.size()

torch.Size([])

In [20]:
torch.tensor([1.1])
torch.tensor([1.1,2.2])
torch.FloatTensor(2)
data = np.ones(2)
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [11]:
x = torch.tensor([1,2,3])
x.new_ones(5,3)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.randn_like(x,dtype=torch.float)

tensor([ 1.0803,  0.2885, -0.8636])

# 索引与切片

In [60]:
a = torch.rand(4,3,28,28)
a[0].shape
a[0,0].shape
a[0,0,2,4]

tensor(0.7720)

In [61]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [62]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [63]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [64]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

In [65]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [66]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

In [70]:
#第0个维度,[0,2]
a.index_select(0,torch.tensor([0,2])).shape

torch.Size([2, 3, 28, 28])

In [71]:
a.index_select(1,torch.tensor([1,2])).shape

torch.Size([4, 2, 28, 28])

In [72]:
a.index_select(2,torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [73]:
a.index_select(2,torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

In [74]:
# ...代表任意维度
a[...].shape

torch.Size([4, 3, 28, 28])

In [75]:
a[0,...].shape

torch.Size([3, 28, 28])

In [76]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [77]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

In [79]:
#masked_select() 
x = torch.randn(3,4)
mask = x.ge(0.5)
torch.masked_select(x, mask)

tensor([0.8636, 1.0981, 0.5400, 1.8245, 2.7244])

# 维度变换

## View/reshpe
保持维度大小不变的情况下,将Tensor变成另外一个维度

In [80]:
a = torch.rand(4,1,28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [81]:
a.view(4,784).shape

torch.Size([4, 784])

In [82]:
b.view(4,784)
b.view(4,28,28,1) #Logic Bug
a.view(4,783) #报错

NameError: ignored

## Squeeze/unsqueeze
挤压
范围 **[-a.dim()-1, a.dim+1)**

In [85]:
a = torch.rand(4,1,28,28)
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [86]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [87]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [88]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [89]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [90]:
a = torch.tensor([1.2,2.3])
a.shape

torch.Size([2])

In [91]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [92]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

In [93]:
# bias相加
b = torch.rand(32)
f = torch.rand(4,32,14,14)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
print(b.shape)

torch.Size([1, 32, 1, 1])


In [94]:
b = torch.rand(1,32,1,1)

In [95]:
b.squeeze().shape

torch.Size([32])

In [96]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [97]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [98]:
b.squeeze(1).shape #维度32,无法挤压

torch.Size([1, 32, 1, 1])

In [ ]:
b.squeeze(-4).shape

## Transpose/t/permute
矩阵转置

In [106]:
a = torch.randn(3,4)
a.t()

tensor([[ 1.1913,  0.2254,  0.2113],
        [-0.0325, -0.5963,  0.3614],
        [ 0.1286,  0.2768,  0.6411],
        [-2.5756, -1.4825, -1.6181]])

In [107]:
 a = torch.rand(4,3,32,32)

In [108]:
a1 = a.transpose(1,3).view(4,3*32*32).view(4,3,32,32)

RuntimeError: ignored

In [109]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)

In [110]:
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)

In [111]:
a1.shape, a2.shape

(torch.Size([4, 3, 32, 32]), torch.Size([4, 3, 32, 32]))

In [112]:
torch.all(torch.eq(a,a1))

tensor(False)

In [113]:
torch.all(torch.eq(a,a2))

tensor(True)

### permute

In [114]:
 a = torch.rand(4,3,28,28)

In [115]:
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [116]:
b = torch.rand(4,3,28,32)

In [117]:
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [118]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [119]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])

## Expand/repeat
维度扩展 Expand: broadcasting
     Repeat: memory copied

In [100]:
b = torch.rand(1,32,1,1) 

In [101]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [102]:
b.expand(-1,32,-1,-1).shape

torch.Size([1, 32, 1, 1])

In [104]:
b.repeat(4,32,1,1).shape #repeat每个维度重复次数

torch.Size([4, 1024, 1, 1])

In [105]:
b.repeat(4,1,1,1).shape   

torch.Size([4, 32, 1, 1])

基于已存在的tensor去操作

查看维度,层到另外一层,矩阵相乘

In [ ]:
torch.tensor([1,2,3]).size()

torch.Size([3])

In [ ]:
torch.randn(5,3).size()[1]

3

运算

In [ ]:
x=torch.randn(5,3)
y=torch.randn(5,3)
x+y

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

In [ ]:
torch.add(x,y)

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

In [ ]:
z = torch.empty(5,3)
torch.add(x,y,out=z)
z

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

In [ ]:
y.add_(x)  #add x to y inplace '_'

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

操作

In [ ]:
np.array([[1,2,3],[4,5,6]])[:,2]

array([3, 6])

In [ ]:
y[:,0]

tensor([-0.0868,  1.0116,  0.2650, -0.5784, -0.4839])

In [ ]:
y.view(-1,5) #-1,基于其他固定，再动态算出

tensor([[-0.0868, -2.4029,  0.2341,  1.0116,  0.5737],
        [-0.2188,  0.2650,  0.8111,  0.7708, -0.5784],
        [-1.2125,  1.1976, -0.4839, -0.9826, -0.3593]])

In [ ]:
y[3,0].item() #非常常用, loss反向传导,打一下日志记录

-0.5784441828727722

更多张量计算可参考
https://zhuanlan.zhihu.com/p/51323438