<a href="https://colab.research.google.com/github/stanshi2016/pytorch_learning/blob/main/%E5%BC%A0%E9%87%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch 

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

# tensor相关的函数和运算

In [5]:
torch.empty(5,3)

tensor([[1.5927e-34, 0.0000e+00, 3.5032e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 7.1463e+22, 4.6241e+30],
        [1.0552e+24, 5.5757e-02, 1.8728e+31],
        [5.9571e-02, 7.0374e+22, 0.0000e+00]])

In [6]:
torch.randn(5,3) #随机初始化的矩阵,包括以后一些网络模型,想去确认一些维度, 模型结构, 可能需要一些数据投喂

tensor([[ 0.8959,  0.4088,  0.2861],
        [-1.0439, -0.3448,  0.3226],
        [ 0.2790,  0.1546, -1.6040],
        [ 0.5428,  0.4197, -2.1450],
        [-1.0152, -0.6445,  0.2172]])

In [10]:
torch.zeros(5,3,dtype=torch.long) #x+y 训练这样一个映射,神经网络y truth_label one-hot表示

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

基于已存在的tensor去操作

In [11]:
x = torch.tensor([1,2,3])
x.new_ones(5,3)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [12]:
torch.randn_like(x,dtype=torch.float)

tensor([ 1.0803,  0.2885, -0.8636])

查看维度,层到另外一层,矩阵相乘

In [13]:
torch.tensor([1,2,3]).size()

torch.Size([3])

In [14]:
torch.randn(5,3).size()[1]

3

运算

In [15]:
x=torch.randn(5,3)
y=torch.randn(5,3)
x+y

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

In [16]:
torch.add(x,y)

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

In [17]:
z = torch.empty(5,3)
torch.add(x,y,out=z)
z

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

In [18]:
y.add_(x)  #add x to y inplace '_'

tensor([[-0.0868, -2.4029,  0.2341],
        [ 1.0116,  0.5737, -0.2188],
        [ 0.2650,  0.8111,  0.7708],
        [-0.5784, -1.2125,  1.1976],
        [-0.4839, -0.9826, -0.3593]])

操作

In [22]:
np.array([[1,2,3],[4,5,6]])[:,2]

array([3, 6])

In [25]:
y[:,0]

tensor([-0.0868,  1.0116,  0.2650, -0.5784, -0.4839])

In [29]:
y.view(-1,5) #-1,基于其他固定，再动态算出

tensor([[-0.0868, -2.4029,  0.2341,  1.0116,  0.5737],
        [-0.2188,  0.2650,  0.8111,  0.7708, -0.5784],
        [-1.2125,  1.1976, -0.4839, -0.9826, -0.3593]])

In [30]:
y[3,0].item() #非常常用, loss反向传导,打一下日志记录

-0.5784441828727722

更多张量计算可参考
https://zhuanlan.zhihu.com/p/51323438